config/routes.rb
Rails.application.routes.draw do
  get 'tvshows/index'

  get 'tvshows/show'

  get 'tvshows/search'

  root 'tvshows#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tvshow.rb
class Tvshow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  include HTTParty
  before_action :populate_showlist, only: [:index]

  def populate_showlist
    @top_shows = []

    5.times do |t|
      response = HTTParty.get("https://api.themoviedb.org/3/discover/tv?api_key=#{ENV["SECRET_API_KEY"]}&language=en-US&sort_by=popularity.desc&page=#{t + 1}&timezone=America%2FNew_York&include_null_first_air_dates=false")
      response["results"].each do |show|
        @top_shows.push(show)
      end
    end
  end


  def index

    @random_message = [
      "...tv is beter with tacos. and we're fresh out of tacos.",
      "...or you could watch 'The Office' for the millienth time?",
      "...spoiler-free since '93.",
      "...we're gonna need a bigger screen.",
      "...couch, blanket, bff, check. check. check.",
      "...number 100 will shock you!...jk couldn't resist",
      "...can we order a pizza?",
      "...I saved girl scout cookies for this exact moment.",
      "...not your common tv guide. now battery operated!",
      "...recommended by 9 out of 10 couch potatoes!",
      "...Smell-O-Vision coming soon.",
      "...because watching people cook never gets old.",
      "...you simply must watch [insert show!]"
    ]

  end

  def show
    @show = {}
    response = HTTParty.get("https://api.themoviedb.org/3/tv/#{params[:tv_id]}?api_key=#{ENV["SECRET_API_KEY"]}")

    if response["poster_path"].nil?
      @show["poster_path_url"] = "error_image.png"
    else
      @show["poster_path_url"] = "https://image.tmdb.org/t/p/original#{response["poster_path"]}"
    end
    @show["name"] = response["name"]
    @show["network_tag_url"] = "https://image.tmdb.org/t/p/original#{response["networks"][0]["logo_path"]}" unless response["networks"].empty?
    @show["created_by"] = response["created_by"][0]["name"] unless response["created_by"].empty?
    @show["number_of_seasons"] = response["number_of_seasons"].to_s unless response["number_of_seasons"].nil?
    @show["number_of_episodes"] = response["number_of_episodes"].to_s unless response["number_of_episodes"].nil?
    @show["genres"] = response["genres"][0]["name"] unless response["genres"].empty?
    @show["type"] = response["type"] unless response["type"].nil?
    @show["origin_country"] = response["origin_country"][0] unless response["origin_country"].empty?
    @show["first_air_date"] = self.fix_date(response["first_air_date"]) unless response["first_air_date"].nil?
    @show["last_air_date"] = self.fix_date(response["last_air_date"]) unless response["last_air_date"].nil?
    @show["overview"] = response["overview"] unless response["overview"].nil?
    @show["justwatch_url"] = "https://www.justwatch.com/us/search?q=#{response['name']}"
  end

  def search
    response = HTTParty.get("https://api.themoviedb.org/3/search/tv?api_key=#{ENV["SECRET_API_KEY"]}&query=#{params[:query]}&page=1")
    @shows = response["results"]
  end

  #used on lines 30-31 to format air_dates
  #from YYYY-MM-DD to MM-DD-YYYY
  def fix_date(date)
    result = date.split("-")
    temp = result[0]
    result[0] = result[1]
    result[1] = result[2]
    result[2] = temp
    result.join("-")
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bingeable</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  </br>
    </br>
    <div class="container">
      <div class="banner">
        <div class="container">
          <div class="row">
            <div class="col-xsm-12">
              <%= link_to "Bingeable.io", root_path, :id => "title_name" %>
            </div>
          </div>
          <div class="row">
            <div class="col-xsm-12" id="logo">
              <%= link_to image_tag('logo2.png', :class => "logo"), root_path %>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <%= form_tag(tvshows_search_path, method: "get") do %>
                <%= text_field_tag(:query, nil, placeholder: "Search TV Shows", :autocomplete => :off, id: "ip-input") %>
                <!-- <%= submit_tag("Search", :class=>"btn btn-primary") %> -->
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/tvshows/index.html.erb
<div class="container">
  <h2 class="jumbotron">Top 100 Shows
    <p>(fresh daily)</p>
    <p><%= "#{@random_message.sample}" %></p>
  </h2>

  <% @top_shows.each_with_index do |show, index| %>
    <div class="card">
      <div class="card-body show_name">
        <h3><%= link_to "#{index + 1}: " + show["name"], tvshows_show_path(:tv_id => show["id"]) %></h3>
      </div>
      <% if show["backdrop_path"].nil? %>
        <%= image_tag("error_image.png", :class => "error-image") %>
      <% else %>
        <%= image_tag("https://image.tmdb.org/t/p/original" + show["backdrop_path"], :class => "img-thumbnail") %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/tvshows/search.html.erb
<div class="container">
  <h2 class="jumbotron bg-success">Search Results</h2>

  <% if @shows.nil? || @shows.empty? %>

    <div class="alert alert-info">
      <strong>Sorry...no results found 😞  Please try again! 👍</strong>
    </div>

  <% else %>

    <% @shows.each_with_index do |show, index| %>
      <div class="card">
        <div class="card-body show_name">
          <h3><%= link_to "#{index + 1}: " + show["name"], tvshows_show_path(:tv_id => show["id"]) %></h3>
        </div>
        <% if show["backdrop_path"].nil? %>
          <%= image_tag("error_image.png", :class => "error-image") %>
        <% else %>
          <%= image_tag("https://image.tmdb.org/t/p/original" + show["backdrop_path"], :class => "img-thumbnail") %>
        <% end %>
        </br>
      </div>
    <% end %>

  <% end %>

</div>

app/views/tvshows/show.html.erb
<div class="card">
  <%=image_tag "#{@show["poster_path_url"]}", :class => "img-thumbnail" %>
    <h3 class="show_name"><%= @show["name"] %></h3>
    <p>Network: <%= image_tag("#{@show["network_tag_url"]}", :class => "network_logo") %>
    <p>Creator: <%= @show["created_by"] %></p>
    <p>Seasons: <%= @show["number_of_seasons"].to_s %></p>
    <p>Episodes: <%= @show["number_of_episodes"].to_s %></p>
    <p>Genre: <%= @show["genres"] %></p>
    <p>Type: <%= @show["type"] %></p>
    <p>Country of Origin: <%= @show["origin_country"] %></p>
    <p>First Air Date: <%= @show["first_air_date"] %></p>
    <p>Most Recent Air Date: <%= @show["last_air_date"] %></p>
    <i id="overview">Overview: <br><%= @show["overview"] %></i>
    <h4><%= link_to "Check out JustWatch.com for currently available streaming options", "#{@show["justwatch_url"]}", :id => "just_watch" %></h4>
  </div>
</div>
</br>